routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
	Route::get('/', function () {
    	return view('admin.auth.login');
	});
    Route::get('/home', 'HomeController@index')->name('admin.home');
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register')->name('admin.register');
    Route::resource('user', 'User\UserController', ['except' => 'show']);
    Route::resource('department', 'User\DepartmentController', ['except' => 'show', 'destroy']);
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController', ['except' => 'show', 'destroy']);
    Route::delete('image/{id}', 'ProductController@deleteImage')->name('admin.image');
    Route::resource('customer', 'CustomerController', ['except' => 'show']);
    Route::resource('producer', 'ProducerController', ['except' => 'show']);
    Route::resource('supplierGroup', 'SupplierGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::post('group', 'ProducerController@createGroup')->name('groupncc');
    Route::resource('table', 'TableController');
    Route::resource('tableGroup', 'TableGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::resource('dealProduct', 'DealProductController', ['except' => 'edit', 'update', 'destroy']);
    Route::post('getProduct', 'DealProductController@getProduct')->name('getProduct');
    Route::resource('billTable', 'BillTableController', ['except' => 'store', 'create', 'destroy', 'edit', 'update']);
    Route::get('sell', 'ReportController@sell')->name('admin.sell');
    Route::post('getSell', 'ReportController@getSell')->name('getSell');
    Route::get('getSellByMonth', 'ReportController@getSellByMonth')->name('getSellByMonth');
    Route::get('products', 'ReportController@product')->name('admin.products');
    Route::post('getProducts', 'ReportController@getProduct')->name('getProducts');
    Route::get('getProductByMonth', 'ReportController@getProductByMonth')->name('getProductByMonth');
    Route::get('customers', 'ReportController@customer')->name('admin.customers');
    Route::get('getCustomers', 'ReportController@getCustomers')->name('getCustomers');
    Route::post('getCustomersByMonth', 'ReportController@getCustomersByMonth')->name('getCustomersByMonth');
    Route::get('producers', 'ReportController@producer')->name('admin.producers');
    Route::get('getProducers', 'ReportController@getProducers')->name('getProducers');
    Route::post('getProducersByMonth', 'ReportController@getProducersByMonth')->name('getProducersByMonth');
    Route::get('employee', 'ReportController@employee')->name('admin.employee');
    Route::get('getEmployees', 'ReportController@getEmployees')->name('getEmployees');
    Route::post('getEmployeesByMonth', 'ReportController@getEmployeesByMonth')->name('getEmployeesByMonth');
    Route::post('homeProducts', 'HomeController@product')->name('home.product');
    Route::get('homeProductsByMonth', 'HomeController@getProductByMonth')->name('home.getProductByMonth');
    Route::get('revenueByDay', 'HomeController@revenueByDay')->name('home.revenueByDay');
});

Route::group(['prefix' => 'receptionist', 'namespace' => 'User\receptionist', 'middleware' => 'receptionist'], function () {
    Route::resource('booking', 'BookingController', ['except' => 'destroy', 'show']);
});

Route::group(['prefix' => 'cashier', 'namespace' => 'User\cashier', 'middleware' => 'cashier'], function () {
    Route::resource('menu', 'MenuController', ['except' => 'edit', 'update', 'destroy', 'create']);
    Route::post('getBooking', 'MenuController@getBooking')->name('getBooking');
    Route::post('getTable', 'MenuController@getTable')->name('getTable');
    Route::post('getMenu', 'MenuController@getMenu')->name('getMenu');
    Route::post('getDetailBill', 'MenuController@getDetailBill')->name('getDetailBill');
    Route::get('table', 'TableController@index')->name('cashier.table');
    Route::post('cashier-table', 'TableController@getTable')->name('cashier.getTable');
    Route::post('cashier-payment', 'MenuController@updatePayment')->name('cashier.payment');
    Route::get('menu-page', 'MenuController@homePage')->name('cashier.menuPage');
    Route::get('table-page', 'TableController@homePage')->name('cashier.tablePage');
});

Route::group(['prefix' => 'chief', 'namespace' => 'User\chief', 'middleware' => 'chief'], function () {
    Route::get('index', 'ChiefController@index')->name('chief.index');
    Route::post('postQuantity', 'ChiefController@postQuantity')->name('chief.postQuantity');
});

app/Http/Controllers/Admin/User/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Department;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $deparments = Department::all();
        return view('admin.users.deparments.index', compact('deparments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.deparments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $department = new Department;
        $department->name = $request->name;
        $department->save();
        return redirect()->route('department.index')->with('success', 'Thêm phòng ban thành công');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = Department::findOrFail($id);
        return view('admin.users.deparments.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $department = Department::findOrFail($id);
        $department->name = $request->name;
        $department->save();
        return redirect()->back()->with('success', 'Sửa thành công');
    }
}

app/Http/Controllers/Admin/User/UserController.php
<?php

namespace App\Http\Controllers\Admin\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Department;
use App\Http\Requests\UsersStoreFormRequest;
use App\Http\Requests\UsersEditFormRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('admin.users.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $UsersStoreFormRequest
     * @return \Illuminate\Http\Response
     */
    public function store(UsersStoreFormRequest $request)
    {
        // $validator = \Validator::make($request->all(), [
        //     'name' => 'required',
        //     'email' => 'required',
        //     'password' => 'required',
        //     'repassword' => 'required',
        // ]);
        
        // if ($validator->fails())
        // {
        //     return response()->json(['errors'=>$validator->errors()->all()]);
        // }
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->avatar = 'default_avatar.png';
        $user->department_id = $request->department;
        $user->save();
        return redirect()->route('user.index')->with('success', 'Thêm tài khoản thành công');
        // return response()->json(['success'=>'Data is successfully added']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $departments = Department::all();
        $selectedParts = $user->department()->pluck('id')->toArray();

        return view('admin.users.edit',compact('user', 'departments', 'selectedParts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UsersEditFormRequest $request, $id)
    {
        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->department_id = $request->department;
        $user->save();
        return redirect()->back()->with('success', 'Sửa thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index')->with('success', 'Xóa thành công');
    }
}

app/Http/Controllers/User/Cashier/MenuController.php
<?php

namespace App\Http\Controllers\User\Cashier;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Booking;
use DB;
use App\Models\BillTableDetail;
use App\Models\BillTable;
use App\Models\Category;
use Auth;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $bookings = Booking::where('status', 0)->orWhere('status', 1)->get();
        $categories = Category::all();
        return view('User.cashier.index', compact('products', 'bookings', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new BillTable;
        $data->date = $request->date;
        $data->customer_id = $request->customer_id;
        $data->status = 0;
        $data->user_id = Auth::user()->id;
        $data->booking_id = $request->booking_id;
        $data->paymented = $request->paymented;
        $quantityunit = $request->quantityunit;
        $unittotal = $request->unittotal;
        $product_id = $request->product_id;
        $data->save();
        $billDetails = array();
        for($i = 0; $i < $request->count; $i++){
            $billDetail = new BillTableDetail(array('quantity' => $quantityunit[$i], 'total' => $unittotal[$i], 'product_id' => $product_id[$i], 'bill_table_id' => $data->id, 'status' => 0));
            $billDetail->save();
            $billDetails[] = $billDetail;
            $product = Product::where('id', $product_id[$i])->first();
            $product->quantity -= $quantityunit[$i];
            $product->save();
        }
        $booking = Booking::findOrFail($request->booking_id);
        $booking->status = 1;
        $booking->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Booking::findOrFail($id);

        return respone()->json($data);
    }

    public function getBooking(Request $request)
    {
        $data = Product::findOrFail($request->product);
        return response ()->json( $data );
    }

    public function getTable(Request $request)
    {
        $data = Booking::select('bookings.id as booking_id','customers.name as name', 'bookings.customer_id', 'bookings.people_number', 'bookings.time')->where('bookings.id', $request->book)->leftjoin('customers', 'bookings.customer_id', '=', 'customers.id')   
        ->get();
        return response ()->json( $data);
    }

    public function getMenu(Request $request)
    {
        
        if($request->category == 0){
            $data = Product::all();
        } else {
            $data = Product::where('category_id', $request->category)->get();
        }
        return response ()->json( $data);
    }

    public function getDetailBill(Request $request) {
        $data = BillTable::select('products.name as nameproduct', 'bill_table_details.quantity as quantityunit', 'bill_table_details.total as totalunit', 'products.sale_price as saleprice', 'bill_table_details.id as proid')
        ->where('customer_id', $request->customer_id)->where('booking_id', $request->booking_id)->where('bill_tables.status', 0)
        ->leftjoin('bill_table_details', 'bill_tables.id', '=', 'bill_table_details.bill_table_id')
        ->leftjoin('products', 'bill_table_details.product_id', '=', 'products.id')
        ->get();
        return response()->json($data);
    }

    public function updatePayment(Request $request) {
        $booking = Booking::findOrFail($request->bookid);
        $billTable = BillTable::where('booking_id', $request->bookid)->first();
        $billTable->status = 1;
        $booking->status = 2;
        $booking->save();
        $billTable->save();
        return $booking;
    }

    public function homePage(){
        $data = Product::all();
        return response()->json($data);
    }
}

app/Http/Controllers/User/Cashier/TableController.php
<?php

namespace App\Http\Controllers\User\Cashier;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\TableGroup;
use App\Models\Table;
use App\Models\Booking;

class TableController extends Controller
{
    public function index() {
    	$groups = TableGroup::all();
    	$bookings = Booking::where('status', 1)->get()->sortByDesc('time');
    	return view('User.cashier.table', compact('groups', 'bookings'));
    }

    public function getTable(Request $request) {
    	if($request->group_id == 0){
    		$data = Table::whereIn('status', [0,2])->get();
    	} else {
    		$data = Table::where('table_group_id', $request->group_id)->whereIn('status', [0,2])->get();
    	}

    	return response()->json($data);
    }

    public function homePage(){
        $data = Table::whereIn('status', [0,2])->get();
        return response()->json($data);
    }
}

app/Http/Controllers/User/Chief/ChiefController.php
<?php

namespace App\Http\Controllers\User\Chief;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\BillTableDetail;
use Carbon;

class ChiefController extends Controller
{
    public function index() {
        $currentTime = Carbon\Carbon::now();
        $products = BillTableDetail::where('bill_table_details.status', 0)
        ->select('tables.name as nametable', 'users.name as nameuser', 'bill_table_details.id', 'bill_table_details.updated_at', 'bill_table_details.quantity', 'products.name as nameproduct')
        ->join('bill_tables', 'bill_tables.id', '=', 'bill_table_details.bill_table_id')
        ->join('bookings', 'bill_tables.booking_id', '=', 'bookings.id')
        ->join('tables', 'bookings.table_id', '=', 'tables.id')
        ->join('users', 'bill_tables.user_id', '=', 'users.id')
        ->join('products', 'bill_table_details.product_id', '=', 'products.id')
        ->get();

    	return view('User.chief.index', compact('products', 'currentTime'));
    }

    public function postQuantity(Request $request) {
        $data = BillTableDetail::findOrFail($request->id);
        if($data->quantity == $request->quantity){
            $data->real_quantity = $request->quantity;
            $data->status = 2;
            $data->save();
        } else {
            $data->real_quantity = $request->quantity;
        }
        $data->save();
    }
}

resources/views/User/receptionist/create.blade.php
@extends('User.layouts.master')
@section('title')
Đặt chỗ
@endsection
@section('CssPage')
{{ Html::style('assets/datetimepicker/build/jquery.datetimepicker.min.css') }}
@endsection
@section('content')
<div class="main-content">
	<div class="container-fluid">
		<div class="page-header">
            <h2 class="header-title">Đặt bàn</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="#" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('booking.index') }}">Đặt bàn</a>
                    <span class="breadcrumb-item active">Tạo mới</span>
                </nav>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Thêm mới đặt bàn</h4>
            </div>
            <form method="POST" action="{{ route('booking.store') }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">khách hàng</label>
                                    <select class="form-control" name="customer">
                                        @foreach($customers as $value)
                                        <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">NV đặt bàn</label>
                                    <input type="text" name="user" readonly="" class="form-control" value="{{ Auth::user()->name }}">
                                    <input type="text" name="user_id" hidden ="" class="form-control" value="{{ Auth::user()->id }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                	<div data-plugin="timepicker">
	                                    <label class="control-label">Giờ đến</label>
	                                    <div class="icon-input">
	                                        <i class="mdi mdi-clock"></i>
	                                        {{ Form::text('time', null, ['class' => 'form-control', 'id' => 'datetimepicker_start_time', 'autocomplete' => 'off']) }}
	                                    </div>
	                                </div>
	                                @if ($errors->has('time'))
		                            <div class="alert alert-danger">
		                                <ul>
		                                    @foreach ($errors->get('time') as $time)
		                                        <li>{{ $time }}</li>
		                                    @endforeach
		                                </ul>
		                            </div>
		                            @endif
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Phòng/Bàn</label>
                                    <select class="form-control" name="table">
                                        @foreach($tables as $value)
                                        <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Số khách</label>
                                    <input type="text" name="people_number" class="form-control">
                                    @if ($errors->has('people_number'))
		                            <div class="alert alert-danger">
		                                <ul>
		                                    @foreach ($errors->get('people_number') as $people_number)
		                                        <li>{{ $people_number }}</li>
		                                    @endforeach
		                                </ul>
		                            </div>
		                            @endif
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Ghi chú</label>
                                    <textarea class="form-control" name="info"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6 offset-md-5">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Tạo mới</button> 
                            </div>
                        </div>
                    </div> 
                </div>  
            </form>  
        </div> 
	</div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/datetimepicker/build/jquery.datetimepicker.full.min.js') }}"></script>
<script>
jQuery('#datetimepicker_start_time').datetimepicker({
	startDate:'+1971/05/01',
	mask:true,
	format:'Y-m-d H:i:s'
});
</script>
@endsection

resources/views/User/receptionist/index.blade.php
@extends('User.layouts.master')
@section('title')
Đặt chỗ
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
	<div class="container-fluid">
		<div class="row">
            <div class="col-md-8">
                <div class="page-header">
                    <h2 class="header-title">Đặt bàn</h2>
                    <div class="header-sub-title">
                        <nav class="breadcrumb breadcrumb-dash">
                            <a href="#" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                            <a class="breadcrumb-item" href="{{ route('booking.index') }}">Đặt bàn</a>
                            <span class="breadcrumb-item active">Danh mục</span>
                        </nav>
                    </div>
                </div> 
            </div>
            <div class="col-md-4">
                <a href="{{ route('booking.create') }}" class="btn btn-success"><span class="fa fa-plus"></span> Đặt bàn</a>
            </div>
        </div>
		<div class="card">
			<div class="card-body">
				<div class="tab-primary">
                    <ul class="nav nav-pills" role="tablist">
                        <li class="nav-item">
                            <a href="#nav-pills-1" class="nav-link active" role="tab" data-toggle="tab">Đang chờ xử lí</a>
                        </li>
                        <li class="nav-item">
                            <a href="#nav-pills-2" class="nav-link" role="tab" data-toggle="tab">Đã hủy</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="nav-pills-1">
                            <div class="p-h-15 p-v-20">
                                <div class="table-overflow">
									<table id="dt-opt" class="table table-hover table-xl">
										<thead>
											<tr>
												<th>
													STT
												</th>
												<th>Khách hàng</th>
												<th>Giờ đến</th>
												<th>Điện thoại</th>
												<th>Số khách</th>
												<th>Phòng/Bàn</th>
												<th>Trạng thái</th>
												<th>Ghi chú</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											@php
												$stt = 1;
											@endphp
											@foreach($book_waits as $value)
											<tr>
												<td>
													{{ $stt++ }}
												</td>
												<td>{{ $value->customer->name }}</td>
												<td>{{ $value->time }}</td>
												<td>{{ $value->customer->phone }}</td>
												<td>{{ $value->people_number }}</td>
												<td>{{ $value->table->name }}</td>
												<td>@if ($value->status == 0)
				                                    <span class="badge badge-gradient-info">đã xếp bàn</span>
				                                    @elseif ($value->status == 1)
				                                    <span class="badge badge-gradient-success">đã nhận bàn</span>
				                                    @elseif ($value->status == 2)
				                                    <span class="badge badge-gradient-warning">quá giờ</span>
				                                    @else
				                                    <span class="badge badge-gradient-danger">hủy đặt</span>
				                                    @endif
				                                </td>
												<td>{{ $value->info }}</td>
												<td class="text-center font-size-18">
													<a href="{{ route('booking.edit', $value->id) }}" class="text-gray m-r-15"><i class="ti-pencil"></i></a>
												</td>
											</tr>
											@endforeach
										</tbody>
									</table>
								</div> 
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="nav-pills-2">
                            <div class="p-h-15 p-v-20">
                                <div class="table-overflow">
									<table id="dt-opt" class="table table-hover table-xl">
										<thead>
											<tr>
												<th>
													STT
												</th>
												<th>Khách hàng</th>
												<th>Giờ đến</th>
												<th>Điện thoại</th>
												<th>Số khách</th>
												<th>Phòng/Bàn</th>
												<th>Trạng thái</th>
												<th>Ghi chú</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											@php
												$stt = 1;
											@endphp
											@foreach($book_refuses as $value)
											<tr>
												<td>
													{{ $stt++ }}
												</td>
												<td>{{ $value->customer->name }}</td>
												<td>{{ $value->time }}</td>
												<td>{{ $value->customer->phone }}</td>
												<td>{{ $value->people_number }}</td>
												<td>{{ $value->table->name }}</td>
												<td>@if ($value->status == 0)
				                                    <span class="badge badge-gradient-info">đang chờ</span>
				                                    @elseif ($value->status == 1)
				                                    <span class="badge badge-gradient-success">đã xếp bàn</span>
				                                    @else
				                                    <span class="badge badge-gradient-danger">hủy đặt</span>
				                                    @endif
				                                </td>
												<td>{{ $value->info }}</td>
												<td class="text-center font-size-18">
													<a href="{{ route('booking.edit', $value->id) }}" class="text-gray m-r-15"><i class="ti-pencil"></i></a>
												</td>
											</tr>
											@endforeach
										</tbody>
									</table>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
				
			</div>       
		</div>
	</div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js') }}"></script>
@endsection