routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
	Route::get('/', function () {
    	return view('admin.auth.login');
	});
    Route::get('/home', 'HomeController@index')->name('admin.home');
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register')->name('admin.register');
    Route::resource('user', 'User\UserController', ['except' => 'show']);
    Route::resource('department', 'User\DepartmentController', ['except' => 'show', 'destroy']);
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController', ['except' => 'show', 'destroy']);
    Route::delete('image/{id}', 'ProductController@deleteImage')->name('admin.image');
    Route::resource('customer', 'CustomerController', ['except' => 'show']);
    Route::resource('producer', 'ProducerController', ['except' => 'show']);
    Route::resource('supplierGroup', 'SupplierGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::post('group', 'ProducerController@createGroup')->name('groupncc');
    Route::resource('table', 'TableController');
    Route::resource('tableGroup', 'TableGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::resource('dealProduct', 'DealProductController', ['except' => 'edit', 'update', 'destroy']);
    Route::post('getProduct', 'DealProductController@getProduct')->name('getProduct');
    Route::resource('billTable', 'BillTableController', ['except' => 'store', 'create', 'destroy', 'edit', 'update']);
    Route::get('sell', 'ReportController@sell')->name('admin.sell');
    Route::post('getSell', 'ReportController@getSell')->name('getSell');
    Route::get('getSellByMonth', 'ReportController@getSellByMonth')->name('getSellByMonth');
    Route::get('products', 'ReportController@product')->name('admin.products');
    Route::post('getProducts', 'ReportController@getProduct')->name('getProducts');
    Route::get('getProductByMonth', 'ReportController@getProductByMonth')->name('getProductByMonth');
    Route::get('customers', 'ReportController@customer')->name('admin.customers');
    Route::get('getCustomers', 'ReportController@getCustomers')->name('getCustomers');
    Route::post('getCustomersByMonth', 'ReportController@getCustomersByMonth')->name('getCustomersByMonth');
    Route::get('producers', 'ReportController@producer')->name('admin.producers');
    Route::get('getProducers', 'ReportController@getProducers')->name('getProducers');
    Route::post('getProducersByMonth', 'ReportController@getProducersByMonth')->name('getProducersByMonth');
    Route::get('employee', 'ReportController@employee')->name('admin.employee');
    Route::get('getEmployees', 'ReportController@getEmployees')->name('getEmployees');
    Route::post('getEmployeesByMonth', 'ReportController@getEmployeesByMonth')->name('getEmployeesByMonth');
    Route::post('homeProducts', 'HomeController@product')->name('home.product');
    Route::get('homeProductsByMonth', 'HomeController@getProductByMonth')->name('home.getProductByMonth');
    Route::get('revenueByDay', 'HomeController@revenueByDay')->name('home.revenueByDay');
});

Route::group(['prefix' => 'receptionist', 'namespace' => 'User\receptionist', 'middleware' => 'receptionist'], function () {
    Route::resource('booking', 'BookingController', ['except' => 'destroy', 'show']);
});

Route::group(['prefix' => 'cashier', 'namespace' => 'User\cashier', 'middleware' => 'cashier'], function () {
    Route::resource('menu', 'MenuController', ['except' => 'edit', 'update', 'destroy', 'create']);
    Route::post('getBooking', 'MenuController@getBooking')->name('getBooking');
    Route::post('getTable', 'MenuController@getTable')->name('getTable');
    Route::post('getMenu', 'MenuController@getMenu')->name('getMenu');
    Route::post('getDetailBill', 'MenuController@getDetailBill')->name('getDetailBill');
    Route::get('table', 'TableController@index')->name('cashier.table');
    Route::post('cashier-table', 'TableController@getTable')->name('cashier.getTable');
    Route::post('cashier-payment', 'MenuController@updatePayment')->name('cashier.payment');
    Route::get('menu-page', 'MenuController@homePage')->name('cashier.menuPage');
    Route::get('table-page', 'TableController@homePage')->name('cashier.tablePage');
});

Route::group(['prefix' => 'chief', 'namespace' => 'User\chief', 'middleware' => 'chief'], function () {
    Route::get('index', 'ChiefController@index')->name('chief.index');
    Route::post('postQuantity', 'ChiefController@postQuantity')->name('chief.postQuantity');
});

app/Http/Controllers/Admin/TableController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Table;
use App\Models\TableGroup;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tables = Table::all();
        return view('admin.tables.index', compact('tables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = TableGroup::all();
        return view('admin.tables.create', compact('groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $table = new Table;
        $table->name = $request->name;
        $table->number_slot = $request->number_slot;
        $table->table_group_id = $request->group;
        $table->info = $request->infosup;
        $table->status = 0;
        $table->save();
        return redirect()->route('table.index')->with('success', 'Tạo bàn thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $table = Table::findOrFail($id);
        $groups = TableGroup::all();
        return view('admin.tables.edit', compact('table', 'groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $table = Table::findOrFail($id);
        $table->name = $request->name;
        $table->number_slot = $request->number_slot;
        $table->table_group_id = $request->group;
        $table->info = $request->info;
        $table->status = $request->status;
        $table->save();
        return redirect()->back()->with('success', 'Chỉnh sửa bàn thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $table = Table::findOrFail($id);
        $table->delete();
        $table->save();
        return redirect()->route('table.index')->with('success', 'Xóa bàn thành công');
    }
}

app/Http/Controllers/User/Cashier/TableController.php
<?php

namespace App\Http\Controllers\User\Cashier;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\TableGroup;
use App\Models\Table;
use App\Models\Booking;

class TableController extends Controller
{
    public function index() {
    	$groups = TableGroup::all();
    	$bookings = Booking::where('status', 1)->get()->sortByDesc('time');
    	return view('User.cashier.table', compact('groups', 'bookings'));
    }

    public function getTable(Request $request) {
    	if($request->group_id == 0){
    		$data = Table::whereIn('status', [0,2])->get();
    	} else {
    		$data = Table::where('table_group_id', $request->group_id)->whereIn('status', [0,2])->get();
    	}

    	return response()->json($data);
    }

    public function homePage(){
        $data = Table::whereIn('status', [0,2])->get();
        return response()->json($data);
    }
}

resources/views/admin/tables/create.blade.php
@extends('admin.layouts.master')
@section('title')
Bàn
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="page-header">
            <h2 class="header-title">Bàn</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('table.index') }}">Bàn</a>
                    <span class="breadcrumb-item active">Tạo mới</span>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Thêm bàn</h4>
            </div>
            <form method="POST" action="{{ route('table.store') }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Tên bàn</label>
                                    <input type="text" class="form-control" name="name">
                                </div>
                            </div>
                            @if ($errors->has('name'))
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->get('name') as $name)
                                        <li>{{ $name }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Số ghế</label>
                                    <input type="address" name="number_slot" class="form-control">
                                </div>
                            </div>
                            @if ($errors->has('number_slot'))
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->get('number_slot') as $number_slot)
                                        <li>{{ $number_slot }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Nhóm</label>
                                    <select class="form-control" name="group">
                                        @foreach($groups as $value)
                                        <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Ghi chú</label>
                                    <textarea class="form-control" name="infosup"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Lưu</button> 
                            </div>
                        </div>
                    </div> 
                </div>  
            </form>  
        </div>   
    </div>
</div>
@endsection
@section('JsPage')
@endsection

resources/views/admin/tables/edit.blade.php
@extends('admin.layouts.master')
@section('title')
bàn
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="page-header">
            <h2 class="header-title">Bàn</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('table.index') }}">Bàn</a>
                    <span class="breadcrumb-item active">Chỉnh sửa</span>
                </nav>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Chỉnh sửa bàn <b>"{{ $table->name }}"</b></h4>
            </div>
            <form method="POST" action="{{ route('table.update', $table->id) }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                {{ method_field('PUT') }}
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Tên bàn</label>
                                    <input type="text" class="form-control" value="{{ $table->name }}" name="name">
                                </div>
                            </div>
                            @if ($errors->has('name'))
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->get('name') as $name)
                                        <li>{{ $name }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Số ghế</label>
                                    <input type="address" name="number_slot" value="{{ $table->number_slot }}" class="form-control">
                                </div>
                            </div>
                            @if ($errors->has('number_slot'))
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->get('number_slot') as $number_slot)
                                        <li>{{ $number_slot }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Nhóm</label>
                                    <select class="form-control" name="group">
                                        @foreach($groups as $value)
                                        <option value="{{ $value->id }}" @if ($value->id == old('group', $table->table_group_id)) selected="selected" @endif>{{ $value->name }}</option>
                                        @endforeach
                                    </select>    
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Ghi chú</label>
                                    <textarea class="form-control" name="info">{{ $table->info }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="text" name="status" value="{{ $table->status }}" hidden="">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Lưu</button> 
                            </div>
                        </div>
                    </div> 
                </div> 
            </form>  
        </div>   
    </div>
</div>
@endsection
@section('JsPage')
@endsection

resources/views/admin/tables/index.blade.php
@extends('admin.layouts.master')
@section('title')
Bàn
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="page-header">
                    <h2 class="header-title">Bàn</h2>
                    <div class="header-sub-title">
                        <nav class="breadcrumb breadcrumb-dash">
                            <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                            <a class="breadcrumb-item" href="{{ route('table.index') }}">Bàn</a>
                            <span class="breadcrumb-item active">Danh mục</span>
                        </nav>
                    </div>
                </div> 
            </div>
        </div>
        <div class="text-right">
          <a href="{{ route('table.create') }}" class="btn btn-success"><span class="fa fa-plus"></span> Bàn</a>
          <a href="{{ route('tableGroup.index') }}" class="btn btn-success"><span class="fa fa-eye"></span> Nhóm</a>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-overflow">
                    <table id="dt-opt" class="table table-hover table-xl">
                        <thead>
                            <tr>
                                <th>
                                    STT
                                </th>
                                <th>Tên</th>
                                <th>Số ghế</th>
                                <th>Trạng thái</th>
                                <th>Vị trí</th>
                                <th>Ghi chú</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $stt = 1;
                            @endphp
                            @foreach($tables as $value)
                            <tr>
                                <td>
                                    {{ $stt++ }}
                                </td>
                                <td data-value="{{ $value }}" data-toggle="modal" data-target="#modal-lg" id = "show-user">{{ $value->name }}
                                </td>
                                <td>{{ $value->number_slot }}</td>
                                <td data-toggle="modal" data-value="{{ $value }}" data-target="#modal-sm" data-url="{{ route('table.update', $value->id) }}"> @if ($value->status == 0)
                                    <span class="badge badge-gradient-info">hoạt động</span>
                                    @elseif ($value->status == 1)
                                    <span class="badge badge-gradient-danger">bảo trì</span>
                                    @else
                                    <span class="badge badge-gradient-warning">đang sử dụng</span>
                                    @endif
                                </td>
                                <td>{{ $value->tableGroup->name }}</td>
                                <td>{{ str_limit($value->info, 10) }}</td>
                                <td class="text-center font-size-18">
                                    <a href="{{ route('table.edit', $value->id) }}" class="text-gray m-r-15"><i class="ti-pencil"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div> 
            </div>       
        </div>
    </div>
    <div class="modal fade" id="modal-lg">
        <div class="modal-dialog modal-lg" role="document">
            <div class="card">
                <div class="card-body">
                    <div class="panel-body">
                        <div class="row">
                            <legend class="avata text-center">{{ __('thông tin bàn') }}</legend>
                            <hr>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ Form::label(__('tên :'), null, ['class' => 'control-label']) }}
                                    <span id ="name"></span>
                                </div>
                                <div class="form-group">
                                    {{ Form::label(__('số ghế :'), null, ['class' => 'control-label']) }}
                                    <span id ="number_slot"></span>
                                </div>
                                <div class="form-group">
                                    {{ Form::label(__('trạng thái :'), null, ['class' => 'control-label']) }}
                                    <span id ="status"></span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    {{ Form::label(__('Ghi chú :'), null, ['class' => 'control-label']) }}
                                    <span id ="info"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-sm">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="m-b-15">Chuyển trạng thái</h4>
                    <form method="POST" id="update-form">
                        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <div class="radio">
                                <input id="radio1" name="status" value="0" type="radio" checked>
                                <label for="radio1">Hoạt động</label>
                            </div>
                            <div class="radio">
                                <input id="radio2" name="status" value="1" type="radio">
                                <label for="radio2">Bảo trì</label>
                            </div>
                            <div class="radio">
                                <input id="radio3" name="status" value="2" type="radio">
                                <label for="radio3">Đang sử dụng</label>
                            </div>
                        </div>
                        <input type="text" name="name" id="name1" hidden="">
                        <input type="text" name="info" id="info1" hidden="">
                        <input type="text" name="group" id="group_id1" hidden="">
                        <input type="text" name="number_slot" id="number_slot1" hidden="">
                        <div class="m-t-20 text-center">
                            <button class="btn btn-default" data-dismiss="modal">Hủy</button>
                            <button class="btn btn-primary" type="submit">Lưu</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js') }}"></script>
<script type="text/javascript">
	$(function() {
		$('#basic-modal').on('show.bs.modal', function(e) {
			var url = $(e.relatedTarget).data('url');
			$('#del-form').attr('action', url);
		});
        $('#modal-lg').on('show.bs.modal', function(e) {
            var value = $(e.relatedTarget).data('value');
            if(value.status == 0) {
                var status = "hoạt động";
            } else if (value.status == 1) {
                var status = "bảo trì";
            } else {
                var status = "đang sử dụng";
            }
            $('#name').text(value.name);
            $('#number_slot').text(value.number_slot);
            $('#status').text(status);
            $('#info').text(value.info);
        });
        $('#modal-sm').on('show.bs.modal', function(e) {
            var url = $(e.relatedTarget).data('url');
            $('#update-form').attr('action', url);
            var value = $(e.relatedTarget).data('value');
            $('#name1').attr('value', value.name);
            $('#number_slot1').attr('value', value.number_slot);
            $('#info1').attr('value', value.info);
            $('#group_id1').attr('value', value.table_group_id);
        });
	});
</script>
@endsection