routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
	Route::get('/', function () {
    	return view('admin.auth.login');
	});
    Route::get('/home', 'HomeController@index')->name('admin.home');
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register')->name('admin.register');
    Route::resource('user', 'User\UserController', ['except' => 'show']);
    Route::resource('department', 'User\DepartmentController', ['except' => 'show', 'destroy']);
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController', ['except' => 'show', 'destroy']);
    Route::delete('image/{id}', 'ProductController@deleteImage')->name('admin.image');
    Route::resource('customer', 'CustomerController', ['except' => 'show']);
    Route::resource('producer', 'ProducerController', ['except' => 'show']);
    Route::resource('supplierGroup', 'SupplierGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::post('group', 'ProducerController@createGroup')->name('groupncc');
    Route::resource('table', 'TableController');
    Route::resource('tableGroup', 'TableGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::resource('dealProduct', 'DealProductController', ['except' => 'edit', 'update', 'destroy']);
    Route::post('getProduct', 'DealProductController@getProduct')->name('getProduct');
    Route::resource('billTable', 'BillTableController', ['except' => 'store', 'create', 'destroy', 'edit', 'update']);
    Route::get('sell', 'ReportController@sell')->name('admin.sell');
    Route::post('getSell', 'ReportController@getSell')->name('getSell');
    Route::get('getSellByMonth', 'ReportController@getSellByMonth')->name('getSellByMonth');
    Route::get('products', 'ReportController@product')->name('admin.products');
    Route::post('getProducts', 'ReportController@getProduct')->name('getProducts');
    Route::get('getProductByMonth', 'ReportController@getProductByMonth')->name('getProductByMonth');
    Route::get('customers', 'ReportController@customer')->name('admin.customers');
    Route::get('getCustomers', 'ReportController@getCustomers')->name('getCustomers');
    Route::post('getCustomersByMonth', 'ReportController@getCustomersByMonth')->name('getCustomersByMonth');
    Route::get('producers', 'ReportController@producer')->name('admin.producers');
    Route::get('getProducers', 'ReportController@getProducers')->name('getProducers');
    Route::post('getProducersByMonth', 'ReportController@getProducersByMonth')->name('getProducersByMonth');
    Route::get('employee', 'ReportController@employee')->name('admin.employee');
    Route::get('getEmployees', 'ReportController@getEmployees')->name('getEmployees');
    Route::post('getEmployeesByMonth', 'ReportController@getEmployeesByMonth')->name('getEmployeesByMonth');
    Route::post('homeProducts', 'HomeController@product')->name('home.product');
    Route::get('homeProductsByMonth', 'HomeController@getProductByMonth')->name('home.getProductByMonth');
    Route::get('revenueByDay', 'HomeController@revenueByDay')->name('home.revenueByDay');
});

Route::group(['prefix' => 'receptionist', 'namespace' => 'User\receptionist', 'middleware' => 'receptionist'], function () {
    Route::resource('booking', 'BookingController', ['except' => 'destroy', 'show']);
});

Route::group(['prefix' => 'cashier', 'namespace' => 'User\cashier', 'middleware' => 'cashier'], function () {
    Route::resource('menu', 'MenuController', ['except' => 'edit', 'update', 'destroy', 'create']);
    Route::post('getBooking', 'MenuController@getBooking')->name('getBooking');
    Route::post('getTable', 'MenuController@getTable')->name('getTable');
    Route::post('getMenu', 'MenuController@getMenu')->name('getMenu');
    Route::post('getDetailBill', 'MenuController@getDetailBill')->name('getDetailBill');
    Route::get('table', 'TableController@index')->name('cashier.table');
    Route::post('cashier-table', 'TableController@getTable')->name('cashier.getTable');
    Route::post('cashier-payment', 'MenuController@updatePayment')->name('cashier.payment');
    Route::get('menu-page', 'MenuController@homePage')->name('cashier.menuPage');
    Route::get('table-page', 'TableController@homePage')->name('cashier.tablePage');
});

Route::group(['prefix' => 'chief', 'namespace' => 'User\chief', 'middleware' => 'chief'], function () {
    Route::get('index', 'ChiefController@index')->name('chief.index');
    Route::post('postQuantity', 'ChiefController@postQuantity')->name('chief.postQuantity');
});

app/Http/Controllers/Admin/TableController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Table;
use App\Models\TableGroup;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tables = Table::all();
        return view('admin.tables.index', compact('tables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = TableGroup::all();
        return view('admin.tables.create', compact('groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $table = new Table;
        $table->name = $request->name;
        $table->number_slot = $request->number_slot;
        $table->table_group_id = $request->group;
        $table->info = $request->infosup;
        $table->status = 0;
        $table->save();
        return redirect()->route('table.index')->with('success', 'Tạo bàn thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $table = Table::findOrFail($id);
        $groups = TableGroup::all();
        return view('admin.tables.edit', compact('table', 'groups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $table = Table::findOrFail($id);
        $table->name = $request->name;
        $table->number_slot = $request->number_slot;
        $table->table_group_id = $request->group;
        $table->info = $request->info;
        $table->status = $request->status;
        $table->save();
        return redirect()->back()->with('success', 'Chỉnh sửa bàn thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $table = Table::findOrFail($id);
        $table->delete();
        $table->save();
        return redirect()->route('table.index')->with('success', 'Xóa bàn thành công');
    }
}

app/Http/Controllers/User/Cashier/TableController.php
<?php

namespace App\Http\Controllers\User\Cashier;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\TableGroup;
use App\Models\Table;
use App\Models\Booking;

class TableController extends Controller
{
    public function index() {
    	$groups = TableGroup::all();
    	$bookings = Booking::where('status', 1)->get()->sortByDesc('time');
    	return view('User.cashier.table', compact('groups', 'bookings'));
    }

    public function getTable(Request $request) {
    	if($request->group_id == 0){
    		$data = Table::whereIn('status', [0,2])->get();
    	} else {
    		$data = Table::where('table_group_id', $request->group_id)->whereIn('status', [0,2])->get();
    	}

    	return response()->json($data);
    }

    public function homePage(){
        $data = Table::whereIn('status', [0,2])->get();
        return response()->json($data);
    }
}

resources/views/admin/tables/group/edit.blade.php
@extends('admin.layouts.master')
@section('title')
nhóm bàn
@endsection
@section('CssPage')
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="page-header">
            <h2 class="header-title">Nhóm bàn</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('tableGroup.index') }}">Nhóm bàn</a>
                    <span class="breadcrumb-item active">Chỉnh sửa</span>
                </nav>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Sửa nhóm nhà cung cấp</h4>
            </div>
            <form method="POST" action="{{ route('tableGroup.update', $group->id) }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                {{ method_field('PUT') }}
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Tên nhóm bàn</label>
                                    <input type="text" class="form-control" value="{{ $group->name }}" name="name">
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Ghi chú</label>
                                    <textarea class="form-control" name="info">{{ $group->info }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Lưu</button> 
                            </div>
                        </div>
                    </div> 
                </div>  
            </form>  
        </div>   
    </div>
</div>
@endsection
@section('JsPage')
@endsection

resources/views/admin/tables/group/index.blade.php
@extends('admin.layouts.master')
@section('title')
nhóm bàn
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
	<div class="container-fluid">
		<div class="page-header">
			<h2 class="header-title">Nhóm bàn</h2>
			<div class="header-sub-title">
				<nav class="breadcrumb breadcrumb-dash">
					<a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
					<a class="breadcrumb-item" href="{{ route('tableGroup.index') }}">Nhóm bàn</a>
					<span class="breadcrumb-item active">Mục lục</span>
				</nav>
			</div>
		</div>
		<div class="text-right">
			<a href="{{ route('table.create') }}" class="btn btn-success"><span class="fa fa-plus"></span> bàn</a>
			<a data-toggle="modal" data-target="#modal-lg" class="btn btn-success"><span class="fa fa-plus"></span> Nhóm bàn</a>
		</div>
		<div class="card">
			<div class="card-body">
				<div class="table-overflow">
					<table id="dt-opt" class="table table-hover table-xl">
						<thead>
							<tr>
								<th>
									STT
								</th>
								<th>Tên</th>
								<th>Ghi chú</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@php
								$stt = 1;
							@endphp
							@foreach($groups as $value)
							<tr>
								<td>
									{{ $stt++ }}
								</td>
								<td>
									{{ $value->name }}
								</td>
								<td>
									{{ $value->info }}
								</td>
								<td class="text-center font-size-18">
									<a href="{{ route('tableGroup.edit', $value->id) }}" class="text-gray m-r-15"><i class="ti-pencil"></i></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div> 
			</div>       
		</div>
		<div class="modal fade" id="modal-lg">
            <div class="modal-dialog" role="document">
                <form method="POST" action="{{ route('tableGroup.store') }}">
                    <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div>
                                <h4 class="d-flex align-items-center h-100 head">Thêm nhóm bàn</h4>
                            </div>
                            <div class="container">
                                <div class="form-group">
                                    <label class="control-label">Tên nhóm bàn</label>
                                    <input type="text" class="form-control" name="nameban">
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Thông tin</label>
                                    <textarea class="form-control" name="info"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer no-border">
                            <div class="modal_button">
                                <div class="row"> 
                                    <button type="reset" class="btn btn-default">Bỏ qua</button>
                                    <button type="submit" name="submit" class="btn btn-primary" id="add">Lưu</button>
                                </div>
                            </div> 
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>  
	</div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js') }}"></script>
@endsection