routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
	Route::get('/', function () {
    	return view('admin.auth.login');
	});
    Route::get('/home', 'HomeController@index')->name('admin.home');
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register')->name('admin.register');
    Route::resource('user', 'User\UserController', ['except' => 'show']);
    Route::resource('department', 'User\DepartmentController', ['except' => 'show', 'destroy']);
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController', ['except' => 'show', 'destroy']);
    Route::delete('image/{id}', 'ProductController@deleteImage')->name('admin.image');
    Route::resource('customer', 'CustomerController', ['except' => 'show']);
    Route::resource('producer', 'ProducerController', ['except' => 'show']);
    Route::resource('supplierGroup', 'SupplierGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::post('group', 'ProducerController@createGroup')->name('groupncc');
    Route::resource('table', 'TableController');
    Route::resource('tableGroup', 'TableGroupController', ['except' => 'show', 'create', 'destroy']);
    Route::resource('dealProduct', 'DealProductController', ['except' => 'edit', 'update', 'destroy']);
    Route::post('getProduct', 'DealProductController@getProduct')->name('getProduct');
    Route::resource('billTable', 'BillTableController', ['except' => 'store', 'create', 'destroy', 'edit', 'update']);
    Route::get('sell', 'ReportController@sell')->name('admin.sell');
    Route::post('getSell', 'ReportController@getSell')->name('getSell');
    Route::get('getSellByMonth', 'ReportController@getSellByMonth')->name('getSellByMonth');
    Route::get('products', 'ReportController@product')->name('admin.products');
    Route::post('getProducts', 'ReportController@getProduct')->name('getProducts');
    Route::get('getProductByMonth', 'ReportController@getProductByMonth')->name('getProductByMonth');
    Route::get('customers', 'ReportController@customer')->name('admin.customers');
    Route::get('getCustomers', 'ReportController@getCustomers')->name('getCustomers');
    Route::post('getCustomersByMonth', 'ReportController@getCustomersByMonth')->name('getCustomersByMonth');
    Route::get('producers', 'ReportController@producer')->name('admin.producers');
    Route::get('getProducers', 'ReportController@getProducers')->name('getProducers');
    Route::post('getProducersByMonth', 'ReportController@getProducersByMonth')->name('getProducersByMonth');
    Route::get('employee', 'ReportController@employee')->name('admin.employee');
    Route::get('getEmployees', 'ReportController@getEmployees')->name('getEmployees');
    Route::post('getEmployeesByMonth', 'ReportController@getEmployeesByMonth')->name('getEmployeesByMonth');
    Route::post('homeProducts', 'HomeController@product')->name('home.product');
    Route::get('homeProductsByMonth', 'HomeController@getProductByMonth')->name('home.getProductByMonth');
    Route::get('revenueByDay', 'HomeController@revenueByDay')->name('home.revenueByDay');
});

Route::group(['prefix' => 'receptionist', 'namespace' => 'User\receptionist', 'middleware' => 'receptionist'], function () {
    Route::resource('booking', 'BookingController', ['except' => 'destroy', 'show']);
});

Route::group(['prefix' => 'cashier', 'namespace' => 'User\cashier', 'middleware' => 'cashier'], function () {
    Route::resource('menu', 'MenuController', ['except' => 'edit', 'update', 'destroy', 'create']);
    Route::post('getBooking', 'MenuController@getBooking')->name('getBooking');
    Route::post('getTable', 'MenuController@getTable')->name('getTable');
    Route::post('getMenu', 'MenuController@getMenu')->name('getMenu');
    Route::post('getDetailBill', 'MenuController@getDetailBill')->name('getDetailBill');
    Route::get('table', 'TableController@index')->name('cashier.table');
    Route::post('cashier-table', 'TableController@getTable')->name('cashier.getTable');
    Route::post('cashier-payment', 'MenuController@updatePayment')->name('cashier.payment');
    Route::get('menu-page', 'MenuController@homePage')->name('cashier.menuPage');
    Route::get('table-page', 'TableController@homePage')->name('cashier.tablePage');
});

Route::group(['prefix' => 'chief', 'namespace' => 'User\chief', 'middleware' => 'chief'], function () {
    Route::get('index', 'ChiefController@index')->name('chief.index');
    Route::post('postQuantity', 'ChiefController@postQuantity')->name('chief.postQuantity');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $table = 'categories';

    protected $fillable = [
        'name',
    ];

    public function products() {
    	return $this->hasMany(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $table = 'products';

    protected $fillable = [
	    'name',
	    'purchase_price',
	    'describe',
	    'sale_price',
	    'bua',
	    'unit',
	    'quantity',
	    'category_id',
        'img',
    ];

    public function images() {
    	return $this->hasMany(Image::class);
    }

    public function category() {
    	return $this->belongsTo(Category::class);
    }

    public function getOneImage($id) {
        $image = Image::where('product_id', $id)->first();
        return $image->name;
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.products.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category;
        $category->name = $request->name;
        $category->save();
        return redirect()->route('category.index')->with('success', 'Thêm phòng ban thành công');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.products.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->save();
        return redirect()->back()->with('success', 'Sửa thành công');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Category;
use App\Models\Image;
use File;
use App\Http\Requests\ProductsStoreFormRequest;
use App\Http\Requests\ProductsEditFormRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ProductsStoreFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product([
            'name' => $request->name,
            'purchase_price' => $request->purchase_price,
            'sale_price' => $request->sale_price,
            'bua' => $request->thucdon,
            'unit' => $request->unit,
            'quantity' => $request->quantity,
            'describe' => $request->describe,
            'category_id' => $request->categories,
        ]);
        $product->save();
        
        if($request->hasFile('image')) {
            foreach($request->image as $image) {
                $filename = $image->getClientOriginalName();
                $image->move(config('app.link_product'), $filename);
 
                $image = new Image([
                    'product_id' => $product->id,
                    'name' => $filename,
                ]);
                
                $image->save();
            }
            $product->img = $filename;
        }
        $product->save();
        return redirect()->route('product.index')->with('success', 'thêm sản phẩm thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        $imageHead = Image::where('product_id', $id)->first();
        $images = Image::where('product_id', $id)->where('id', '!=', $imageHead->id)->get();
        return view('admin.products.show', compact('product', 'images', 'imageHead'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::all();
        $images = Image::where('product_id', $id)->get();
        $selectedCategory = $product->category()->pluck('id')->toArray();
        $selectedBua = $product->pluck('bua')->toArray();
        return view('admin.products.edit', compact('product', 'categories', 'images', 'selectedCategory', 'selectedBua'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ProductsEditFormRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->name = $request->name;
        $product->purchase_price = $request->purchase_price;
        $product->sale_price = $request->sale_price;
        $product->bua = $request->thucdon;
        $product->unit = $request->unit;
        $product->quantity = $request->quantity;
        $product->describe = $request->describe;
        $product->category_id = $request->categories;
        $product->save();
        if($request->hasFile('image')) {
            foreach($request->image as $image) {
                $filename = $image->getClientOriginalName();
                $image->move(config('app.link_product'), $filename);
 
                $image = new Image([
                    'product_id' => $product->id,
                    'name' => $filename,
                ]);
                
                $image->save();
            }
        }
        return redirect()->back()->with('success', 'cập nhật sản phẩm thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        $product->save();
        return redirect()->route('product.index')->with('success', 'Xóa sản phẩm thành công');
    }

    public function deleteImage($id)
    {
        $image = Image::findOrFail($id);
        $imageCount = Image::where('name', $image->name)->count();
        $filename = $image->name;
        if($imageCount == 1) {
            File::delete(config('app.link_product') . $filename);
        }
        $image->delete();
        $image->save();
        return redirect()->route('product.index')->with('success', 'Xóa ảnh thành công');
    }
}

resources/views/admin/products/category/create.blade.php
@extends('admin.layouts.master')
@section('title')
product
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="page-header">
            <h2 class="header-title">Chủng loại</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('category.index') }}">Chủng loại</a>
                    <span class="breadcrumb-item active">Tạo mới</span>
                </nav>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Thêm chủng loại</h4>
            </div>
            <form method="POST" action="{{ route('category.store') }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Tên chủng loại</label>
                                    <input type="text" class="form-control" name="name" required="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Lưu</button> 
                            </div>
                        </div>
                    </div> 
                </div>  
            </form>  
        </div>   
    </div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js"></script>
@endsection

resources/views/admin/products/category/edit.blade.php
@extends('admin.layouts.master')
@section('title')
product
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
    <div class="container-fluid">
        <div class="page-header">
            <h2 class="header-title">Chủng loại</h2>
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" href="{{ route('category.index') }}">Chủng loại</a>
                    <span class="breadcrumb-item active">Chỉnh sửa</span>
                </nav>
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header border bottom">
                <h4 class="card-title">Sửa chủng loại</h4>
            </div>
            <form method="POST" action="{{ route('category.update', $category->id) }}">
                <input type="hidden" name="_token" value="{!! csrf_token() !!}">
                {{ method_field('PUT') }}
                <div class="card-body">
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <div class="form-group">
                                    <label class="control-label">Tên chủng loại</label>
                                    <input type="text" class="form-control" value="{{ $category->name }}" name="name">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row m-t-30">
                        <div class="col-md-6">
                            <div class="p-h-10">
                                <button type="reset" class="btn btn-default">Bỏ qua</button>
                                <button type="submit" name="submit" class="btn btn-primary">Lưu</button> 
                            </div>
                        </div>
                    </div> 
                </div>  
            </form>  
        </div>   
    </div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js"></script>
@endsection

resources/views/admin/products/category/index.blade.php
@extends('admin.layouts.master')
@section('title')
product
@endsection
@section('CssPage')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables/media/css/dataTables.bootstrap4.min.css') }}" />
@endsection
@section('content')
<div class="main-content">
	<div class="container-fluid">
		<div class="page-header">
			<h2 class="header-title">Chủng loại</h2>
			<div class="header-sub-title">
				<nav class="breadcrumb breadcrumb-dash">
					<a href="{{ route('admin.home') }}" class="breadcrumb-item"><i class="ti-home p-r-5"></i>Trang chủ</a>
					<a class="breadcrumb-item" href="{{ route('category.index') }}">Chủng loại</a>
					<span class="breadcrumb-item active">Mục lục</span>
				</nav>
			</div>
		</div>
		<div class="text-right">
			<a href="{{ route('category.create') }}" class="btn btn-success"><span class="fa fa-plus"></span> Chủng loại</a>
		</div>
		<div class="card">
			<div class="card-body">
				<div class="table-overflow">
					<table id="dt-opt" class="table table-hover table-xl">
						<thead>
							<tr>
								<th>
									STT
								</th>
								<th>Tên</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@php
								$stt = 1;
							@endphp
							@foreach($categories as $value)
							<tr>
								<td>
									{{ $stt++ }}
								</td>
								<td>
									{{ $value->name }}
								</td>
								<td class="text-center font-size-18">
									<a href="{{ route('category.edit', $value->id) }}" class="text-gray m-r-15"><i class="ti-pencil"></i></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div> 
			</div>       
		</div>
	</div>
</div>
@endsection
@section('JsPage')
<script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/tables/data-table.js') }}"></script>
@endsection